import {
  Geist,
  Geist_Mono,
  Work_Sans,
  Inter,
  Urbanist,
  Montserrat,
  Poppins,
  Mulish,
  Manrope,
} from "next/font/google";
import Header from "../components/organisms/Header";
import Footar from "../components/organisms/Footar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-work-sans",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // required weights
  variable: "--font-montserrat", // CSS variable for Tailwind
});

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-urbanist",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

const mulish = Mulish({
  subsets: ["latin"],
  weight: ["900"], // Black weight
  variable: "--font-mulish",
});

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["700"], // Bold
  variable: "--font-manrope",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${mulish.variable} ${poppins.variable} ${manrope.variable} ${geistMono.variable} ${workSans.variable} ${urbanist.variable} ${montserrat.variable} ${inter.variable}`}
    >
      <body className="antialiased bg-white text-gray-900">
        <Header />
        {children}
        <Footar />
      </body>
    </html>
  );
}
